name: Run Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Lấy mã nguồn từ kho lưu trữ
      - name: Checkout repository
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Bước 3: Cài đặt các thư viện yêu cầu
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước 4: Chạy bot Telegram
      - name: Run Telegram Bot
        run: |
          nohup python bot.py &

      # Bước 5: Kiểm tra nếu bot đang chạy (Optional)
      - name: Check bot process
        run: |
          ps aux | grep bot.py
